version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: unless-stopped
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: mongodb
    networks:
      - neuvue
    volumes:
      - mongo-data:/data/db
  # keycloak-proxy:
  #   image: 256215146792.dkr.ecr.us-east-1.amazonaws.com/colocar/keycloak-proxy.js
  #   restart: unless-stopped
  #   labels:
  #     co.elastic.logs/enabled: true
  #     co.elastic.logs/json.keys_under_root: true
  #     co.elastic.logs/json.add_error_key: true
  #   environment:
  #     NODE_ENV: production
  #     VIRTUAL_HOST: ${COLOCARD_VIRTUAL_HOST}
  #     LETSENCRYPT_HOST: ${COLOCARD_LETSENCRYPT_HOST}
  #     LETSENCRYPT_EMAIL: ${COLOCARD_LETSENCRYPT_EMAIL}
  #   networks:
  #     - colocard
  #   volumes:
  #     - ./configs/keycloak-proxy-config.yml:/etc/keycloak-proxy.js/production.yml:ro
  #   depends_on:
  #     - mongodb
  neuvue-queue:
    image: 473318664541.dkr.ecr.us-east-1.amazonaws.com/aplbrain/neuvue-queue
    restart: unless-stopped
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.add_error_key: true
    environment:
      COLOCARD_MONGODB_DATABASE: colocard
      COLOCARD_MONGODB_HOST: mongodb
      VIRTUAL_HOST: queue.neuvue.io
      LETSENCRYPT_HOST: queue.neuvue.io
    networks:
      - neuvue
    volumes:
      - ./configs/colocard-config.json:/etc/colocard/production.json:ro
    depends_on:
      - mongodb
  mongo-grove:
    image: 473318664541.dkr.ecr.us-east-1.amazonaws.com/aplbrain/mongo-grove
    container_name: colocard-mongo-grove
    restart: unless-stopped
    labels:
      co.elastic.logs/enabled: true
    environment:
      ARCHIVE_NAME: neuvue-queue-data-backup.gz
      MONGO_HOST: mongodb
      S3_BUCKET: neuvue-queue-data
    networks:
      - neuvue
    depends_on:
      - mongodb
networks:
  neuvue:
    external: true
volumes:
  mongo-data:
