version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: unless-stopped
    networks:
      - neuvue
    volumes:
      - mongo-data:/data/db
      - /data/archive:/data/archive/
  neuvue-queue:
    #image: 473318664541.dkr.ecr.us-east-1.amazonaws.com/aplbrain/neuvue-queue
    image: neuvue-test:staging
    restart: unless-stopped
    environment:
      NEUVUEQUEUE_MONGODB_DATABASE: neuvue
      NEUVUEQUEUE_MONGODB_HOST: mongodb
      VIRTUAL_HOST: queue.neuvue.io
      LETSENCRYPT_HOST: queue.neuvue.io
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_CLIENTID: ${AUTH0_CLIENTID}
      AUTH0CLIENTSECRET: ${AUTH0CLIENTSECRET}
    networks:
      - neuvue
    volumes:
      - ./configs/neuvue-config.json:/etc/neuvue-queue/default.json:ro
    depends_on:
      - mongodb
  # mongo-grove:
  #   image: 473318664541.dkr.ecr.us-east-1.amazonaws.com/aplbrain/mongo-grove
  #   container_name: neuvue-mongo-grove
  #   restart: unless-stopped
  #   environment:
  #     ARCHIVE_NAME: neuvue-queue-data-backup.gz
  #     MONGO_HOST: mongodb
  #     S3_BUCKET: neuvue-queue-data
  #   networks:
  #     - neuvue
  #   depends_on:
  #     - mongodb
networks:
  neuvue:
    external: true
volumes:
  mongo-data:
