version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: unless-stopped
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: mongodb
    networks:
      - neuvue
    volumes:
      - mongo-data:/data/db
  neuvue-queue:
    #image: 473318664541.dkr.ecr.us-east-1.amazonaws.com/aplbrain/neuvue-queue
    image: neuvue-test:staging
    restart: unless-stopped
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.add_error_key: true
    environment:
      NEUVUEQUEUE_MONGODB_DATABASE: neuvue
      NEUVUEQUEUE_MONGODB_HOST: mongodb
      VIRTUAL_HOST: dev-queue.neuvue.io
      LETSENCRYPT_HOST: dev-queue.neuvue.io
      AUTH0_DOMAIN: dev-oe-jgl7m.us.auth0.com
      AUTH0_AUDIENCE: https://queue.neuvue.io
    networks:
      - neuvue
    volumes:
      - ./configs/neuvue-config.json:/etc/neuvue-queue/default.json:ro
    depends_on:
      - mongodb
  mongo-grove:
    image: 473318664541.dkr.ecr.us-east-1.amazonaws.com/aplbrain/mongo-grove
    container_name: neuvue-mongo-grove
    restart: unless-stopped
    labels:
      co.elastic.logs/enabled: true
    environment:
      ARCHIVE_NAME: neuvue-queue-data-backup.gz
      MONGO_HOST: mongodb
      S3_BUCKET: neuvue-queue-data
    networks:
      - neuvue
    depends_on:
      - mongodb
networks:
  neuvue:
    external: true
volumes:
  mongo-data:
