keycloak-host: auth.bossdb.io
keycloak-realm: BOSS
host: 0.0.0.0
port: 80
upstream: http://0.0.0.0:9005
resources:
  - uri: ^/$
    methods:
      - GET
    whitelisted: true
  - uri: ^/docs/.*
    methods:
      - GET
    whitelisted: true
  - uri: ^/swagger/.*
    methods:
      - GET
    whitelisted: true
  - uri: ^/.+
    methods:
      - OPTIONS
    whitelisted: true
  - uri: ^/(tasks|points).*
    methods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
      - DELETE
    users:
      - joycejm1
      - lkitche2
      - lunada1
      - ramsddc1
      - roseva1
      - romerkj1
      - rtenaza1
      - xenesd1