keycloak-host: auth.theboss.io
keycloak-realm: BOSS
upstream: http://colocard:9005
resources:
  - uri: ^/$
    methods:
      - GET
    whitelisted: true
  - uri: ^/docs/.*
    methods:
      - GET
    whitelisted: true
  - uri: ^/swagger/.*
    methods:
      - GET
    whitelisted: true
  - uri: ^/.+
    methods:
      - OPTIONS
    whitelisted: true
  - uri: ^/(graphs|nodes|questions|volumes).*
    methods:
      - GET
      - HEAD
      - POST
      - PUT
      - PATCH
    users:
      - cabishop
      - will
      - downsjt1
      - miller
      - j6m8
      - rivlinp
      - cordish25
      - jcampb87
      - nrafi1
      - ysalaza1
      - rm
      - msanch35
      - laurentpark
      - oremor12
      - kahmed4
      - justinj
      - jheiko1
      - dxenes1
      - dramsde1
      - cmentor2
      - kevintorgas
      - chamia.dorsey
      - nyajones
      - kporte18
      - michisantangelo
      - afrazi13
      - omarti
      - rrais3
      - hannahparis
  - uri: ^/(graphs|nodes|questions|volumes).*
    methods:
      - DELETE
    users:
      - cabishop
      - will
      - downsjt1
      - miller
      - j6m8
