keycloak-host: auth.theboss.io
keycloak-realm: BOSS
upstream: http://colocard:9005
resources:
- uri: ^/*
  methods:
  - OPTIONS
  whitelisted: true
- uri: ^/*
  methods:
  - GET
  - HEAD
  - POST
  - PUT
  - DELETE
  - PATCH
  users:
  - cabishop
  - will
  - downsjt1
  - miller
  - j6m8
  - rivlinp
  - cordish25
  - jcampb87
  - nrafi1
  - ysalaza1
  - rm
  - msanch35
  - laurentpark
  - oremor12
  - kahmed4
  - justinj
  - jheiko1
  - dxenes1
  - dramsde1
  - cmentor2
  - kevintorgas
  - chamia.dorsey
  - njones55
  - kporte18
  - michisantangelo
  - afrazi13
  - omarti
