port: 80
keycloak-host: auth.theboss.io
keycloak-realm: BOSS
upstream: http://colocard
resources:
- uri: ^/*
  methods:
  - OPTIONS
  whitelisted: true
- uri: ^/*
  methods:
  - GET
  - HEAD
  - POST
  - PUT
  - DELETE
  - PATCH
  users:
  - cabishop
  - will
  - downsjt1
  - miller
  - j6m8