version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    restart: unless-stopped
    command: ["-e", "-strict.perms=false", "--modules", "nginx,mongodb"]
    user: root
    networks:
      - neuvue
      - elk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
networks:
  neuvue:
    external: true
  elk:
    external: true
