version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    restart: unless-stopped
    environment:
      discovery.type: single-node
    networks:
      - elk
    volumes:
      - esdata:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    restart: unless-stopped
    networks:
      - elk
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    restart: unless-stopped
    environment:
      VIRTUAL_HOST: ${ELK_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${ELK_LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${ELK_LETSENCRYPT_EMAIL}
    networks:
      - elk
    depends_on:
      - elasticsearch
networks:
  elk:
    external: true
volumes:
  esdata:
